### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cellularmitosis** [CHiPs44/YetAnotherPicoComputer#8]
I just wanted to say thanks so much for putting all of this together.  I was thinking about building a boot-to-lang console microcomputer using the pico and this set of docs and references gives a great lay of the land.  Hugely helpful.

Feel free to close this issue after reading.  Thanks again!

**Comment by CHiPs44** [comment]
Hello,

I added some thoughts about [RP2350 possibilities](https://github.com/CHiPs44/YetAnotherPicoComputer/blob/main/50-Setup-with-RP2350.md).

Perhaps it's worth a star on the project?

;-)
